# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger/api/v1/greeting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmessenger/api/v1/greeting.proto\x12\x02v1\"\x1f\n\x0fGreetingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x10GreetingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2H\n\x0fGreetingService\x12\x35\n\x08SayHello\x12\x13.v1.GreetingRequest\x1a\x14.v1.GreetingResponseb\x06proto3')



_GREETINGREQUEST = DESCRIPTOR.message_types_by_name['GreetingRequest']
_GREETINGRESPONSE = DESCRIPTOR.message_types_by_name['GreetingResponse']
GreetingRequest = _reflection.GeneratedProtocolMessageType('GreetingRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGREQUEST,
  '__module__' : 'messenger.api.v1.greeting_pb2'
  # @@protoc_insertion_point(class_scope:v1.GreetingRequest)
  })
_sym_db.RegisterMessage(GreetingRequest)

GreetingResponse = _reflection.GeneratedProtocolMessageType('GreetingResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETINGRESPONSE,
  '__module__' : 'messenger.api.v1.greeting_pb2'
  # @@protoc_insertion_point(class_scope:v1.GreetingResponse)
  })
_sym_db.RegisterMessage(GreetingResponse)

_GREETINGSERVICE = DESCRIPTOR.services_by_name['GreetingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GREETINGREQUEST._serialized_start=39
  _GREETINGREQUEST._serialized_end=70
  _GREETINGRESPONSE._serialized_start=72
  _GREETINGRESPONSE._serialized_end=107
  _GREETINGSERVICE._serialized_start=109
  _GREETINGSERVICE._serialized_end=181
# @@protoc_insertion_point(module_scope)
