# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger/api/v1/messenger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n messenger/api/v1/messenger.proto\x12\x02v1\"\x1b\n\x19GetServerPublicKeyRequest\")\n\x1aGetServerPublicKeyResponse\x12\x0b\n\x03key\x18\x01 \x01(\t2a\n\x10MessengerService\x12M\n\x0cGetPublicKey\x12\x1d.v1.GetServerPublicKeyRequest\x1a\x1e.v1.GetServerPublicKeyResponseb\x06proto3')



_GETSERVERPUBLICKEYREQUEST = DESCRIPTOR.message_types_by_name['GetServerPublicKeyRequest']
_GETSERVERPUBLICKEYRESPONSE = DESCRIPTOR.message_types_by_name['GetServerPublicKeyResponse']
GetServerPublicKeyRequest = _reflection.GeneratedProtocolMessageType('GetServerPublicKeyRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSERVERPUBLICKEYREQUEST,
  '__module__' : 'messenger.api.v1.messenger_pb2'
  # @@protoc_insertion_point(class_scope:v1.GetServerPublicKeyRequest)
  })
_sym_db.RegisterMessage(GetServerPublicKeyRequest)

GetServerPublicKeyResponse = _reflection.GeneratedProtocolMessageType('GetServerPublicKeyResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSERVERPUBLICKEYRESPONSE,
  '__module__' : 'messenger.api.v1.messenger_pb2'
  # @@protoc_insertion_point(class_scope:v1.GetServerPublicKeyResponse)
  })
_sym_db.RegisterMessage(GetServerPublicKeyResponse)

_MESSENGERSERVICE = DESCRIPTOR.services_by_name['MessengerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETSERVERPUBLICKEYREQUEST._serialized_start=40
  _GETSERVERPUBLICKEYREQUEST._serialized_end=67
  _GETSERVERPUBLICKEYRESPONSE._serialized_start=69
  _GETSERVERPUBLICKEYRESPONSE._serialized_end=110
  _MESSENGERSERVICE._serialized_start=112
  _MESSENGERSERVICE._serialized_end=209
# @@protoc_insertion_point(module_scope)
