# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from messenger.api.v1 import messenger_pb2 as messenger_dot_api_dot_v1_dot_messenger__pb2


class MessengerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRSAPublicKey = channel.unary_unary(
                '/v1.MessengerService/GetRSAPublicKey',
                request_serializer=messenger_dot_api_dot_v1_dot_messenger__pb2.GetRSAPublicKeyRequest.SerializeToString,
                response_deserializer=messenger_dot_api_dot_v1_dot_messenger__pb2.GetRSAPublicKeyResponse.FromString,
                )
        self.GetDHParameters = channel.unary_unary(
                '/v1.MessengerService/GetDHParameters',
                request_serializer=messenger_dot_api_dot_v1_dot_messenger__pb2.GetDHParametersRequest.SerializeToString,
                response_deserializer=messenger_dot_api_dot_v1_dot_messenger__pb2.SignedMessage.FromString,
                )
        self.GetDHPublicKey = channel.unary_unary(
                '/v1.MessengerService/GetDHPublicKey',
                request_serializer=messenger_dot_api_dot_v1_dot_messenger__pb2.GetDHPublicKeyRequest.SerializeToString,
                response_deserializer=messenger_dot_api_dot_v1_dot_messenger__pb2.SignedMessage.FromString,
                )
        self.Register = channel.unary_unary(
                '/v1.MessengerService/Register',
                request_serializer=messenger_dot_api_dot_v1_dot_messenger__pb2.RegisterRequest.SerializeToString,
                response_deserializer=messenger_dot_api_dot_v1_dot_messenger__pb2.RegisterResponse.FromString,
                )
        self.StartSession = channel.stream_stream(
                '/v1.MessengerService/StartSession',
                request_serializer=messenger_dot_api_dot_v1_dot_messenger__pb2.TypedMessage.SerializeToString,
                response_deserializer=messenger_dot_api_dot_v1_dot_messenger__pb2.SignedMessage.FromString,
                )


class MessengerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRSAPublicKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDHParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDHPublicKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessengerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRSAPublicKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRSAPublicKey,
                    request_deserializer=messenger_dot_api_dot_v1_dot_messenger__pb2.GetRSAPublicKeyRequest.FromString,
                    response_serializer=messenger_dot_api_dot_v1_dot_messenger__pb2.GetRSAPublicKeyResponse.SerializeToString,
            ),
            'GetDHParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDHParameters,
                    request_deserializer=messenger_dot_api_dot_v1_dot_messenger__pb2.GetDHParametersRequest.FromString,
                    response_serializer=messenger_dot_api_dot_v1_dot_messenger__pb2.SignedMessage.SerializeToString,
            ),
            'GetDHPublicKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDHPublicKey,
                    request_deserializer=messenger_dot_api_dot_v1_dot_messenger__pb2.GetDHPublicKeyRequest.FromString,
                    response_serializer=messenger_dot_api_dot_v1_dot_messenger__pb2.SignedMessage.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=messenger_dot_api_dot_v1_dot_messenger__pb2.RegisterRequest.FromString,
                    response_serializer=messenger_dot_api_dot_v1_dot_messenger__pb2.RegisterResponse.SerializeToString,
            ),
            'StartSession': grpc.stream_stream_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=messenger_dot_api_dot_v1_dot_messenger__pb2.TypedMessage.FromString,
                    response_serializer=messenger_dot_api_dot_v1_dot_messenger__pb2.SignedMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.MessengerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessengerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRSAPublicKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v1.MessengerService/GetRSAPublicKey',
            messenger_dot_api_dot_v1_dot_messenger__pb2.GetRSAPublicKeyRequest.SerializeToString,
            messenger_dot_api_dot_v1_dot_messenger__pb2.GetRSAPublicKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDHParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v1.MessengerService/GetDHParameters',
            messenger_dot_api_dot_v1_dot_messenger__pb2.GetDHParametersRequest.SerializeToString,
            messenger_dot_api_dot_v1_dot_messenger__pb2.SignedMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDHPublicKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v1.MessengerService/GetDHPublicKey',
            messenger_dot_api_dot_v1_dot_messenger__pb2.GetDHPublicKeyRequest.SerializeToString,
            messenger_dot_api_dot_v1_dot_messenger__pb2.SignedMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v1.MessengerService/Register',
            messenger_dot_api_dot_v1_dot_messenger__pb2.RegisterRequest.SerializeToString,
            messenger_dot_api_dot_v1_dot_messenger__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/v1.MessengerService/StartSession',
            messenger_dot_api_dot_v1_dot_messenger__pb2.TypedMessage.SerializeToString,
            messenger_dot_api_dot_v1_dot_messenger__pb2.SignedMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
