# Generated by Django 4.1.1 on 2023-06-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("value", models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddIndex(
            model_name="configuration",
            index=models.Index(fields=["name"], name="messenger_c_name_980abd_idx"),
        ),
    ]
