# Generated by Django 4.1.1 on 2023-06-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0007_request_alter_groupchatmember_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="rsa_public_key",
            field=models.BinaryField(default=None),
            preserve_default=False,
        ),
    ]
