# Generated by Django 4.1.1 on 2023-07-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0007_request_session_rsa_public_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverkey",
            name="encrypted_value",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
