# Generated by Django 4.1.1 on 2023-07-01 16:17

from django.db import migrations, models
from django.conf import settings
from messenger.utils import sha256_hash, encrypt_aes, decrypt_aes


def encrypt_serverkeys(apps, schema_editor):
    ServerKey = apps.get_model("messenger", "ServerKey")
    aes_key = sha256_hash(settings.SECRET_KEY.encode())
    for serverkey in ServerKey.objects.all():
        serverkey.encrypted_value = encrypt_aes(serverkey.value, aes_key)
        serverkey.save()


def decrypt_serverkeys(apps, schema_editor):
    ServerKey = apps.get_model("messenger", "ServerKey")
    aes_key = sha256_hash(settings.SECRET_KEY.encode())
    for serverkey in ServerKey.objects.all():
        serverkey.value = decrypt_aes(serverkey.encrypted_value, aes_key)
        serverkey.save()


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0008_serverkey_encrypted_value"),
    ]

    operations = [
        migrations.RunPython(encrypt_serverkeys, decrypt_serverkeys)
    ]
