# Generated by Django 4.1.1 on 2023-07-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0009_encrypt_serverkeys"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="dh_shared_secret",
            new_name="encrypted_dh_shared_secret",
        ),
        migrations.RemoveField(model_name="serverkey", name="value",),
    ]
